---
title: "St. Lucia - RBM Diagnosis"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "CLEAR LAC"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: 
      collapsed: TRUE
      smooth_scroll: TRUE
    number_sections: FALSE

date: "`r format(Sys.time(), '%d %B %Y')`"
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.align = 'center', echo = TRUE)

```

```{r data, include = FALSE}
library(readr)
library(tidyverse)
library(ggplot2)
library(readxl)

add_rbm <- function(file, n){
  
  RBM_info <- read_excel(file, sheet = 1)
  RBM_info <- arrange(RBM_info, sub_id)
  for( i in 2:n){
    
    aux <- read_excel(file, sheet = i)
    aux <- arrange(aux, sub_id)
    RBM_info <- bind_rows(RBM_info, aux)
    
  }
  
  RBM_info <- RBM_info %>% 
    select( bullet_id, sub_id, comment) %>% 
    mutate(bullet_id = as.integer(bullet_id), sub_id = as.integer(sub_id)) 
  
  return(RBM_info)
  
}



RBM <- add_rbm("RBM_com_clean_StLucia.xlsx",19)
RBM_ideal <- read_excel("RBM_ideal.xlsx")

RBM_ideal <- RBM_ideal %>%  
            mutate( dimension_d = case_when(  
              Dimension == 1 ~ "Institutionalization",
              Dimension == 2 ~ "Implementation",
              Dimension == 3 ~ "Technical",
              Dimension == 4 ~  "Use",
              ) ) %>% 
            select(dimension = Dimension, dimension_d, bullet_id, sub_id, indicator) 

RBM_full <- left_join(RBM,RBM_ideal)


```



```{r report, results = 'asis' , echo = FALSE}

for ( i in 1:4){
  
  
  stage_1 <- RBM_ideal %>% 
            filter( dimension == i)
  cat(paste0( "---\n\n"))
  
  cat(paste0( "# ", stage_1$dimension_d[1], " \n\n"))
  
  for( j in min(stage_1$bullet_id):max(stage_1$bullet_id)){
    
    
    stage_2 <- stage_1 %>% 
            filter( bullet_id == j)
    
    cat(paste0( "### ", j, ".  ", filter(stage_2, sub_id == 0)$indicator[1], " {.tabset .tabset-pills} \n\n"))
    
    
    intro <- RBM_full %>% 
            filter( dimension == i) %>% 
            filter( bullet_id == j) %>% 
            filter( sub_id == 0) %>%
            mutate(comment = str_replace_all(comment, "\\*", " - "))
    
    cat(paste0( ifelse(str_detect(intro$comment, "-"), " ", " "), intro$comment, sep = "\n\n"  ))
    
    for( k in 1:max(stage_2$sub_id)){
      
      stage_3 <- RBM_full %>% 
            filter( dimension == i) %>% 
            filter( bullet_id == j) %>% 
            filter( sub_id == k)
      
      cat(paste0( "\n\n#### Sub-element  ",k, " {-} \n\n"))
      
      cat(paste0( " > ", filter(stage_2, sub_id == k)$indicator[1]), "\n\n")
      
      
      cat(paste0(ifelse(str_detect(stage_3$comment, "\\*"), "\t", " - "), stage_3$comment ), sep = "\n\n")
      cat("\n\n")
      
      
      
    }
    
    cat(paste0( "### {.unlisted .toc-ignore}", " \n\n"))
    
    
  }
  

}


```




